# Supabase Configuration

[db]
major_version = 15

[api]
enabled = true

[studio]
enabled = true

[auth]
enable_signup = true
jwt_expiry = 3600
jwt_secret = "your-jwt-secret-16-chars-minimum"

[realtime]
enabled = true
